#! /bin/bash

# Small script to automate generating
# a stripped PDF from an URL

## CHECKS
# exit on any error
set -e

# Where should files ultimately be moved?
dest_dir=$HOME"/files/syncthing/Inbox/"

################
## START SCRIPT

# STARTUP
echo "\n"
echo "=---------------"
echo "= PERCOLLATE PDF"
echo "= efls"
echo ""

# Read URL
echo "----------\n"
echo "Enter URL:"
read -r url

# Read filename
echo "-----------\n"
echo "Enter name:"
read -r name

# Read tag
echo "-----------\n"
echo "Enter tag:"
read -r tag

# Generate tslink
tslink="ts$(date +%y%m)$tag"

# Generate destination filename
filename="$name $tslink.pdf"

echo "Destination is $filename"
echo "------------------------\n"

# Run percollate
echo "Now percollate!"
percollate pdf --no-amp --template ./html.html --style ./css.css -o "$filename" "$url"

echo "Moving PDF to $dest_dir..."
mv "$filename" "$dest_dir"

echo "\n"
echo "Opening $filename..."
open "$dest_dir/$filename"

